// Paires de mots pour Undercover : deux mots proches mais distincts.
// Chaque catégorie contient un tableau de paires [motCivil, motUndercover].
const WORD_CATEGORIES = [
  {
    name: "Animaux",
    pairs: [
      ["Chat", "Chien"],
      ["Lion", "Tigre"],
      ["Cheval", "Âne"],
      ["Aigle", "Faucon"],
      ["Baleine", "Dauphin"],
      ["Serpent", "Lézard"],
      ["Abeille", "Guêpe"],
      ["Renard", "Loup"],
      ["Hibou", "Chouette"],
      ["Tortue", "Escargot"],
    ],
  },
  {
    name: "Nourriture & Boissons",
    pairs: [
      ["Café", "Thé"],
      ["Pizza", "Tarte"],
      ["Chocolat", "Vanille"],
      ["Vin", "Bière"],
      ["Pomme", "Poire"],
      ["Riz", "Pâtes"],
      ["Beurre", "Margarine"],
      ["Fromage", "Yaourt"],
      ["Citron", "Orange"],
      ["Soupe", "Ragoût"],
    ],
  },
  {
    name: "Objets du quotidien",
    pairs: [
      ["Stylo", "Crayon"],
      ["Parapluie", "Casquette"],
      ["Valise", "Sac à dos"],
      ["Montre", "Horloge"],
      ["Miroir", "Fenêtre"],
      ["Bougie", "Lampe"],
      ["Couteau", "Ciseaux"],
      ["Oreiller", "Couverture"],
      ["Clé", "Serrure"],
      ["Chaise", "Tabouret"],
    ],
  },
  {
    name: "Métiers",
    pairs: [
      ["Médecin", "Infirmier"],
      ["Professeur", "Directeur"],
      ["Policier", "Pompier"],
      ["Boulanger", "Pâtissier"],
      ["Avocat", "Juge"],
      ["Acteur", "Réalisateur"],
      ["Chanteur", "Musicien"],
      ["Pilote", "Steward"],
      ["Journaliste", "Écrivain"],
      ["Coiffeur", "Esthéticienne"],
    ],
  },
  {
    name: "Lieux",
    pairs: [
      ["Plage", "Piscine"],
      ["Montagne", "Colline"],
      ["Forêt", "Jungle"],
      ["Hôpital", "Clinique"],
      ["École", "Université"],
      ["Restaurant", "Café"],
      ["Aéroport", "Gare"],
      ["Musée", "Bibliothèque"],
      ["Désert", "Savane"],
      ["Village", "Ville"],
    ],
  },
  {
    name: "Sports",
    pairs: [
      ["Football", "Rugby"],
      ["Tennis", "Badminton"],
      ["Natation", "Plongée"],
      ["Boxe", "Judo"],
      ["Basketball", "Handball"],
      ["Ski", "Snowboard"],
      ["Cyclisme", "Course à pied"],
      ["Golf", "Bowling"],
      ["Escalade", "Randonnée"],
      ["Volleyball", "Beach-volley"],
    ],
  },
  {
    name: "Technologie",
    pairs: [
      ["Smartphone", "Tablette"],
      ["Ordinateur", "Laptop"],
      ["Télévision", "Écran"],
      ["Internet", "Wifi"],
      ["Robot", "Drone"],
      ["Clavier", "Souris"],
      ["Casque", "Écouteurs"],
      ["Imprimante", "Scanner"],
      ["Batterie", "Chargeur"],
      ["Caméra", "Appareil photo"],
    ],
  },
  {
    name: "Nature",
    pairs: [
      ["Rivière", "Lac"],
      ["Volcan", "Montagne"],
      ["Tempête", "Ouragan"],
      ["Neige", "Glace"],
      ["Soleil", "Lune"],
      ["Arbre", "Buisson"],
      ["Fleur", "Plante"],
      ["Nuage", "Brouillard"],
      ["Île", "Presqu'île"],
      ["Étoile", "Planète"],
    ],
  },
  {
    name: "Transport",
    pairs: [
      ["Voiture", "Camion"],
      ["Vélo", "Moto"],
      ["Train", "Tramway"],
      ["Avion", "Hélicoptère"],
      ["Bateau", "Voilier"],
      ["Bus", "Métro"],
      ["Taxi", "VTC"],
      ["Fusée", "Navette"],
      ["Trottinette", "Skateboard"],
      ["Camping-car", "Caravane"],
    ],
  },
  {
    name: "Personnages",
    pairs: [
      ["Super-héros", "Vilain"],
      ["Roi", "Reine"],
      ["Pirate", "Corsaire"],
      ["Sorcier", "Magicien"],
      ["Vampire", "Zombie"],
      ["Chevalier", "Gladiateur"],
      ["Fantôme", "Squelette"],
      ["Ninja", "Samouraï"],
      ["Détective", "Espion"],
      ["Clown", "Magicien de cirque"],
    ],
  },
  {
    name: "Corps & Santé",
    pairs: [
      ["Rhume", "Grippe"],
      ["Fatigue", "Insomnie"],
      ["Migraine", "Vertige"],
      ["Fièvre", "Frisson"],
      ["Allergie", "Intolérance"],
      ["Dentiste", "Orthodontiste"],
      ["Vaccin", "Médicament"],
      ["Fracture", "Entorse"],
      ["Massage", "Étirement"],
      ["Régime", "Jeûne"],
    ],
  },
  {
    name: "Concepts",
    pairs: [
      ["Amour", "Amitié"],
      ["Rêve", "Cauchemar"],
      ["Rire", "Sourire"],
      ["Silence", "Calme"],
      ["Bonheur", "Joie"],
      ["Peur", "Angoisse"],
      ["Chance", "Destin"],
      ["Mensonge", "Secret"],
      ["Liberté", "Indépendance"],
      ["Patience", "Persévérance"],
    ],
  },
];
