// Paires de mots pour Undercover : deux mots proches mais distincts.
// Chaque catégorie contient un tableau de paires [motCivil, motUndercover].
const WORD_CATEGORIES = [
  {
    name: "Animaux",
    pairs: [
      ["Chat", "Chien"],
      ["Lion", "Tigre"],
      ["Cheval", "Âne"],
      ["Aigle", "Faucon"],
      ["Baleine", "Dauphin"],
      ["Serpent", "Lézard"],
      ["Abeille", "Guêpe"],
      ["Renard", "Loup"],
      ["Hibou", "Chouette"],
      ["Tortue", "Escargot"],
      ["Grenouille", "Crapaud"],
      ["Souris", "Rat"],
      ["Cerf", "Chevreuil"],
      ["Requin", "Orque"],
      ["Panthère", "Léopard"],
      ["Corbeau", "Pie"],
      ["Chameau", "Dromadaire"],
      ["Perroquet", "Perruche"],
      ["Hérisson", "Taupe"],
      ["Girafe", "Zèbre"],
      ["Ours", "Panda"],
      ["Poule", "Coq"],
      ["Mouton", "Chèvre"],
      ["Crocodile", "Alligator"],
      ["Papillon", "Libellule"],
      ["Pieuvre", "Calamar"],
      ["Écureuil", "Marmotte"],
      ["Vautour", "Charognard"],
      ["Scorpion", "Araignée"],
      ["Flamant rose", "Cigogne"],
    ],
  },
  {
    name: "Nourriture & Boissons",
    pairs: [
      ["Café", "Thé"],
      ["Pizza", "Tarte"],
      ["Chocolat", "Vanille"],
      ["Vin", "Bière"],
      ["Pomme", "Poire"],
      ["Riz", "Pâtes"],
      ["Beurre", "Margarine"],
      ["Fromage", "Yaourt"],
      ["Citron", "Orange"],
      ["Soupe", "Ragoût"],
      ["Sandwich", "Burger"],
      ["Crêpe", "Gaufre"],
      ["Confiture", "Miel"],
      ["Sel", "Poivre"],
      ["Sucre", "Sirop"],
      ["Lait", "Crème"],
      ["Jus d'orange", "Limonade"],
      ["Pain", "Baguette"],
      ["Biscuit", "Gâteau"],
      ["Glace", "Sorbet"],
      ["Salade", "Crudités"],
      ["Omelette", "Œuf au plat"],
      ["Frites", "Chips"],
      ["Saucisse", "Merguez"],
      ["Poulet", "Dinde"],
      ["Champagne", "Cidre"],
      ["Chocolat chaud", "Café au lait"],
      ["Nouilles", "Spaghetti"],
      ["Sushi", "Sashimi"],
      ["Ketchup", "Mayonnaise"],
    ],
  },
  {
    name: "Objets du quotidien",
    pairs: [
      ["Stylo", "Crayon"],
      ["Parapluie", "Casquette"],
      ["Valise", "Sac à dos"],
      ["Montre", "Horloge"],
      ["Miroir", "Fenêtre"],
      ["Bougie", "Lampe"],
      ["Couteau", "Ciseaux"],
      ["Oreiller", "Couverture"],
      ["Clé", "Serrure"],
      ["Chaise", "Tabouret"],
      ["Balai", "Serpillière"],
      ["Brosse à dents", "Peigne"],
      ["Savon", "Shampoing"],
      ["Serviette", "Éponge"],
      ["Poubelle", "Sac plastique"],
      ["Portefeuille", "Porte-monnaie"],
      ["Lunettes", "Loupe"],
      ["Ceinture", "Cravate"],
      ["Cintre", "Étagère"],
      ["Boîte à outils", "Trousse"],
      ["Réveil", "Chronomètre"],
      ["Batterie", "Pile"],
      ["Tapis", "Paillasson"],
      ["Rideau", "Store"],
      ["Cadenas", "Chaîne"],
    ],
  },
  {
    name: "Métiers",
    pairs: [
      ["Médecin", "Infirmier"],
      ["Professeur", "Directeur"],
      ["Policier", "Pompier"],
      ["Boulanger", "Pâtissier"],
      ["Avocat", "Juge"],
      ["Acteur", "Réalisateur"],
      ["Chanteur", "Musicien"],
      ["Pilote", "Steward"],
      ["Journaliste", "Écrivain"],
      ["Coiffeur", "Esthéticienne"],
      ["Boucher", "Charcutier"],
      ["Architecte", "Ingénieur"],
      ["Plombier", "Électricien"],
      ["Vétérinaire", "Dresseur"],
      ["Facteur", "Livreur"],
      ["Serveur", "Cuisinier"],
      ["Comptable", "Banquier"],
      ["Agriculteur", "Jardinier"],
      ["Menuisier", "Charpentier"],
      ["Pharmacien", "Chimiste"],
      ["Photographe", "Peintre"],
      ["Traducteur", "Interprète"],
      ["Douanier", "Agent de sécurité"],
      ["Mécanicien", "Garagiste"],
      ["Marin", "Pêcheur"],
    ],
  },
  {
    name: "Lieux",
    pairs: [
      ["Plage", "Piscine"],
      ["Montagne", "Colline"],
      ["Forêt", "Jungle"],
      ["Hôpital", "Clinique"],
      ["École", "Université"],
      ["Restaurant", "Café"],
      ["Aéroport", "Gare"],
      ["Musée", "Bibliothèque"],
      ["Désert", "Savane"],
      ["Village", "Ville"],
      ["Supermarché", "Marché"],
      ["Église", "Cathédrale"],
      ["Parc", "Jardin"],
      ["Cinéma", "Théâtre"],
      ["Hôtel", "Auberge"],
      ["Prison", "Caserne"],
      ["Usine", "Entrepôt"],
      ["Château", "Palais"],
      ["Port", "Quai"],
      ["Grotte", "Caverne"],
      ["Cimetière", "Monastère"],
      ["Stade", "Gymnase"],
      ["Camping", "Refuge"],
      ["Banque", "Bureau de poste"],
      ["Zoo", "Aquarium"],
    ],
  },
  {
    name: "Sports",
    pairs: [
      ["Football", "Rugby"],
      ["Tennis", "Badminton"],
      ["Natation", "Plongée"],
      ["Boxe", "Judo"],
      ["Basketball", "Handball"],
      ["Ski", "Snowboard"],
      ["Cyclisme", "Course à pied"],
      ["Golf", "Bowling"],
      ["Escalade", "Randonnée"],
      ["Volleyball", "Beach-volley"],
      ["Karaté", "Taekwondo"],
      ["Patinage", "Danse sur glace"],
      ["Voile", "Aviron"],
      ["Équitation", "Polo"],
      ["Gymnastique", "Trampoline"],
      ["Fléchettes", "Billard"],
      ["Surf", "Bodyboard"],
      ["Athlétisme", "Marathon"],
      ["Water-polo", "Polo"],
      ["Skate", "Roller"],
    ],
  },
  {
    name: "Technologie",
    pairs: [
      ["Smartphone", "Tablette"],
      ["Ordinateur", "Laptop"],
      ["Télévision", "Écran"],
      ["Internet", "Wifi"],
      ["Robot", "Drone"],
      ["Clavier", "Souris"],
      ["Casque", "Écouteurs"],
      ["Imprimante", "Scanner"],
      ["Batterie", "Chargeur"],
      ["Caméra", "Appareil photo"],
      ["Console", "Manette"],
      ["Application", "Logiciel"],
      ["Mot de passe", "Code secret"],
      ["Réseau social", "Messagerie"],
      ["Antivirus", "Pare-feu"],
      ["Disque dur", "Clé USB"],
      ["Enceinte", "Haut-parleur"],
      ["Satellite", "Antenne"],
      ["Réalité virtuelle", "Hologramme"],
      ["Intelligence artificielle", "Algorithme"],
    ],
  },
  {
    name: "Nature",
    pairs: [
      ["Rivière", "Lac"],
      ["Volcan", "Montagne"],
      ["Tempête", "Ouragan"],
      ["Neige", "Glace"],
      ["Soleil", "Lune"],
      ["Arbre", "Buisson"],
      ["Fleur", "Plante"],
      ["Nuage", "Brouillard"],
      ["Île", "Presqu'île"],
      ["Étoile", "Planète"],
      ["Vent", "Brise"],
      ["Pluie", "Averse"],
      ["Éclair", "Tonnerre"],
      ["Cascade", "Torrent"],
      ["Marée", "Vague"],
      ["Séisme", "Tremblement de terre"],
      ["Arc-en-ciel", "Aurore boréale"],
      ["Racine", "Tronc"],
      ["Feuille", "Pétale"],
      ["Falaise", "Précipice"],
    ],
  },
  {
    name: "Transport",
    pairs: [
      ["Voiture", "Camion"],
      ["Vélo", "Moto"],
      ["Train", "Tramway"],
      ["Avion", "Hélicoptère"],
      ["Bateau", "Voilier"],
      ["Bus", "Métro"],
      ["Taxi", "VTC"],
      ["Fusée", "Navette"],
      ["Trottinette", "Skateboard"],
      ["Camping-car", "Caravane"],
      ["Sous-marin", "Yacht"],
      ["Tracteur", "Bulldozer"],
      ["Montgolfière", "Planeur"],
      ["Traîneau", "Motoneige"],
      ["Ferry", "Paquebot"],
      ["Ambulance", "Fourgon"],
      ["Téléphérique", "Funiculaire"],
      ["Charrette", "Chariot"],
    ],
  },
  {
    name: "Personnages",
    pairs: [
      ["Super-héros", "Vilain"],
      ["Roi", "Reine"],
      ["Pirate", "Corsaire"],
      ["Sorcier", "Magicien"],
      ["Vampire", "Zombie"],
      ["Chevalier", "Gladiateur"],
      ["Fantôme", "Squelette"],
      ["Ninja", "Samouraï"],
      ["Détective", "Espion"],
      ["Clown", "Magicien de cirque"],
      ["Prince", "Princesse"],
      ["Dragon", "Griffon"],
      ["Loup-garou", "Sorcière"],
      ["Robot géant", "Cyborg"],
      ["Extraterrestre", "Alien"],
      ["Géant", "Ogre"],
      ["Elfe", "Nain"],
      ["Momie", "Zombie"],
      ["Ange", "Démon"],
      ["Cowboy", "Shérif"],
    ],
  },
  {
    name: "Corps & Santé",
    pairs: [
      ["Rhume", "Grippe"],
      ["Fatigue", "Insomnie"],
      ["Migraine", "Vertige"],
      ["Fièvre", "Frisson"],
      ["Allergie", "Intolérance"],
      ["Dentiste", "Orthodontiste"],
      ["Vaccin", "Médicament"],
      ["Fracture", "Entorse"],
      ["Massage", "Étirement"],
      ["Régime", "Jeûne"],
      ["Toux", "Éternuement"],
      ["Cicatrice", "Bleu"],
      ["Pansement", "Bandage"],
      ["Chirurgie", "Opération"],
      ["Stéthoscope", "Thermomètre"],
      ["Béquille", "Fauteuil roulant"],
      ["Piqûre", "Prise de sang"],
      ["Sommeil", "Sieste"],
    ],
  },
  {
    name: "Concepts",
    pairs: [
      ["Amour", "Amitié"],
      ["Rêve", "Cauchemar"],
      ["Rire", "Sourire"],
      ["Silence", "Calme"],
      ["Bonheur", "Joie"],
      ["Peur", "Angoisse"],
      ["Chance", "Destin"],
      ["Mensonge", "Secret"],
      ["Liberté", "Indépendance"],
      ["Patience", "Persévérance"],
      ["Jalousie", "Envie"],
      ["Colère", "Frustration"],
      ["Espoir", "Optimisme"],
      ["Tristesse", "Nostalgie"],
      ["Courage", "Audace"],
      ["Honnêteté", "Sincérité"],
      ["Sagesse", "Intelligence"],
      ["Curiosité", "Étonnement"],
      ["Générosité", "Gentillesse"],
      ["Fierté", "Orgueil"],
    ],
  },
  {
    name: "Fruits & Légumes",
    pairs: [
      ["Fraise", "Framboise"],
      ["Banane", "Plantain"],
      ["Carotte", "Panais"],
      ["Tomate", "Poivron"],
      ["Ananas", "Mangue"],
      ["Pastèque", "Melon"],
      ["Raisin", "Groseille"],
      ["Courgette", "Concombre"],
      ["Oignon", "Échalote"],
      ["Pomme de terre", "Patate douce"],
      ["Cerise", "Prune"],
      ["Kiwi", "Litchi"],
      ["Brocoli", "Chou-fleur"],
      ["Champignon", "Truffe"],
      ["Ail", "Gingembre"],
      ["Épinard", "Salade verte"],
      ["Citrouille", "Potiron"],
      ["Avocat", "Olive"],
    ],
  },
  {
    name: "Vêtements",
    pairs: [
      ["Chemise", "T-shirt"],
      ["Pantalon", "Jean"],
      ["Robe", "Jupe"],
      ["Manteau", "Veste"],
      ["Chaussures", "Baskets"],
      ["Chapeau", "Bonnet"],
      ["Écharpe", "Foulard"],
      ["Gants", "Moufles"],
      ["Pull", "Gilet"],
      ["Short", "Bermuda"],
      ["Costume", "Smoking"],
      ["Maillot de bain", "Combinaison"],
      ["Sandales", "Tongs"],
      ["Bottes", "Chaussons"],
      ["Pyjama", "Chemise de nuit"],
      ["Ceinture", "Bretelles"],
    ],
  },
  {
    name: "Musique & Instruments",
    pairs: [
      ["Guitare", "Basse"],
      ["Piano", "Clavier"],
      ["Violon", "Alto"],
      ["Batterie", "Percussion"],
      ["Flûte", "Clarinette"],
      ["Trompette", "Trombone"],
      ["Chanson", "Mélodie"],
      ["Concert", "Festival"],
      ["Orchestre", "Fanfare"],
      ["Rap", "Slam"],
      ["Rock", "Metal"],
      ["Jazz", "Blues"],
      ["Opéra", "Comédie musicale"],
      ["Micro", "Haut-parleur"],
      ["Accordéon", "Harmonica"],
    ],
  },
  {
    name: "École & Études",
    pairs: [
      ["Cahier", "Classeur"],
      ["Stylo", "Feutre"],
      ["Examen", "Contrôle"],
      ["Récréation", "Pause"],
      ["Maths", "Physique"],
      ["Histoire", "Géographie"],
      ["Bibliothèque", "Salle d'étude"],
      ["Tableau", "Vidéoprojecteur"],
      ["Cartable", "Sac à dos"],
      ["Devoir", "Exposé"],
      ["Rentrée", "Vacances"],
      ["Diplôme", "Certificat"],
      ["Bourse", "Prêt étudiant"],
      ["Cantine", "Réfectoire"],
    ],
  },
  {
    name: "Fêtes & Événements",
    pairs: [
      ["Anniversaire", "Fête"],
      ["Mariage", "Fiançailles"],
      ["Noël", "Nouvel An"],
      ["Halloween", "Carnaval"],
      ["Feu d'artifice", "Pétard"],
      ["Cadeau", "Surprise"],
      ["Gâteau d'anniversaire", "Bougie"],
      ["Karaoké", "Soirée dansante"],
      ["Défilé", "Parade"],
      ["Pique-nique", "Barbecue"],
      ["Réveillon", "Banquet"],
      ["Déguisement", "Costume"],
    ],
  },
  {
    name: "Météo & Saisons",
    pairs: [
      ["Été", "Printemps"],
      ["Hiver", "Automne"],
      ["Canicule", "Vague de froid"],
      ["Sécheresse", "Inondation"],
      ["Brouillard", "Brume"],
      ["Grêle", "Verglas"],
      ["Coup de soleil", "Insolation"],
      ["Bourrasque", "Rafale"],
    ],
  },
  {
    name: "Argent & Commerce",
    pairs: [
      ["Pièce", "Billet"],
      ["Salaire", "Prime"],
      ["Impôt", "Taxe"],
      ["Facture", "Ticket de caisse"],
      ["Investissement", "Épargne"],
      ["Prêt", "Crédit"],
      ["Solde", "Promotion"],
      ["Actions", "Bourse"],
      ["Portefeuille", "Coffre-fort"],
      ["Enchère", "Vente aux enchères"],
    ],
  },
  {
    name: "Formes & Couleurs",
    pairs: [
      ["Cercle", "Ovale"],
      ["Carré", "Rectangle"],
      ["Triangle", "Losange"],
      ["Rouge", "Orange"],
      ["Bleu", "Turquoise"],
      ["Vert", "Kaki"],
      ["Jaune", "Doré"],
      ["Noir", "Gris"],
      ["Rose", "Violet"],
      ["Blanc", "Beige"],
      ["Cube", "Sphère"],
      ["Cylindre", "Cône"],
    ],
  },
  {
    name: "Cinéma & Séries",
    pairs: [
      ["Film", "Série"],
      ["Acteur", "Actrice"],
      ["Réalisateur", "Producteur"],
      ["Scénario", "Script"],
      ["Comédie", "Drame"],
      ["Horreur", "Thriller"],
      ["Documentaire", "Reportage"],
      ["Bande-annonce", "Générique"],
      ["Cascadeur", "Doublure"],
      ["Sous-titres", "Doublage"],
      ["Blockbuster", "Film indépendant"],
      ["Animation", "Dessin animé"],
    ],
  },
  {
    name: "Internet & Réseaux sociaux",
    pairs: [
      ["Message", "Notification"],
      ["Post", "Story"],
      ["Like", "Commentaire"],
      ["Abonné", "Abonnement"],
      ["Vidéo", "Live"],
      ["Hashtag", "Tendance"],
      ["Influenceur", "Créateur de contenu"],
      ["Email", "SMS"],
      ["Mot de passe", "Identifiant"],
      ["Podcast", "Chaîne"],
      ["Site web", "Application"],
      ["Cookie", "Cache"],
    ],
  },
  {
    name: "Jeux",
    pairs: [
      ["Échecs", "Dames"],
      ["Cartes", "Dominos"],
      ["Puzzle", "Casse-tête"],
      ["Console", "Ordinateur"],
      ["Dés", "Roulette"],
      ["Cache-cache", "Chat perché"],
      ["Mots croisés", "Sudoku"],
      ["Poupée", "Peluche"],
      ["Toupie", "Yoyo"],
      ["Cerf-volant", "Frisbee"],
      ["Balançoire", "Toboggan"],
    ],
  },
  {
    name: "Maison & Meubles",
    pairs: [
      ["Canapé", "Fauteuil"],
      ["Table", "Bureau"],
      ["Lit", "Matelas"],
      ["Armoire", "Commode"],
      ["Étagère", "Bibliothèque"],
      ["Cuisine", "Salle à manger"],
      ["Salon", "Chambre"],
      ["Balcon", "Terrasse"],
      ["Garage", "Cave"],
      ["Cheminée", "Radiateur"],
      ["Douche", "Baignoire"],
      ["Évier", "Lavabo"],
    ],
  },
  {
    name: "Outils & Bricolage",
    pairs: [
      ["Marteau", "Maillet"],
      ["Tournevis", "Clé à molette"],
      ["Perceuse", "Visseuse"],
      ["Scie", "Hache"],
      ["Pince", "Tenaille"],
      ["Échelle", "Escabeau"],
      ["Peinture", "Vernis"],
      ["Colle", "Ruban adhésif"],
      ["Clou", "Vis"],
      ["Niveau", "Mètre ruban"],
    ],
  },
  {
    name: "Espace & Astronomie",
    pairs: [
      ["Étoile", "Comète"],
      ["Planète", "Astéroïde"],
      ["Galaxie", "Constellation"],
      ["Astronaute", "Cosmonaute"],
      ["Fusée", "Satellite"],
      ["Trou noir", "Supernova"],
      ["Télescope", "Observatoire"],
      ["Météorite", "Comète"],
      ["Éclipse", "Aurore boréale"],
    ],
  },
  {
    name: "Mythologie & Légendes",
    pairs: [
      ["Zeus", "Poséidon"],
      ["Dragon", "Phénix"],
      ["Sirène", "Nymphe"],
      ["Titan", "Géant"],
      ["Licorne", "Pégase"],
      ["Sphinx", "Minotaure"],
      ["Oracle", "Prophète"],
      ["Centaure", "Satyre"],
    ],
  },
  {
    name: "Géographie & Pays",
    pairs: [
      ["France", "Belgique"],
      ["Italie", "Espagne"],
      ["Japon", "Chine"],
      ["Canada", "États-Unis"],
      ["Brésil", "Argentine"],
      ["Égypte", "Maroc"],
      ["Allemagne", "Autriche"],
      ["Suisse", "Luxembourg"],
      ["Portugal", "Grèce"],
      ["Inde", "Pakistan"],
      ["Russie", "Ukraine"],
      ["Australie", "Nouvelle-Zélande"],
      ["Mexique", "Colombie"],
      ["Suède", "Norvège"],
    ],
  },
  {
    name: "Desserts & Sucreries",
    pairs: [
      ["Tarte aux pommes", "Tarte au citron"],
      ["Mousse au chocolat", "Crème brûlée"],
      ["Macaron", "Financier"],
      ["Bonbon", "Chewing-gum"],
      ["Nougat", "Caramel"],
      ["Cookie", "Muffin"],
      ["Éclair", "Religieuse"],
      ["Meringue", "Chantilly"],
      ["Sorbet", "Granité"],
      ["Croissant", "Pain au chocolat"],
    ],
  },
  {
    name: "Émotions & Expressions",
    pairs: [
      ["Sourire", "Rire aux éclats"],
      ["Pleurer", "Sangloter"],
      ["Crier", "Chuchoter"],
      ["Bâiller", "S'étirer"],
      ["Rougir", "Pâlir"],
      ["Trembler", "Frissonner"],
      ["Sursauter", "Sursaut"],
      ["Applaudir", "Acclamer"],
    ],
  },
  {
    name: "Phénomènes & Catastrophes",
    pairs: [
      ["Tsunami", "Raz-de-marée"],
      ["Incendie", "Explosion"],
      ["Avalanche", "Glissement de terrain"],
      ["Tornade", "Cyclone"],
      ["Panne d'électricité", "Coupure de courant"],
      ["Naufrage", "Accident"],
    ],
  },
  {
    name: "Boissons",
    pairs: [
      ["Eau gazeuse", "Eau plate"],
      ["Soda", "Jus de fruit"],
      ["Cocktail", "Mocktail"],
      ["Whisky", "Rhum"],
      ["Champagne", "Vin mousseux"],
      ["Smoothie", "Milkshake"],
      ["Infusion", "Tisane"],
      ["Café glacé", "Chocolat glacé"],
    ],
  },
  {
    name: "Communication",
    pairs: [
      ["Lettre", "Carte postale"],
      ["Appel", "Visioconférence"],
      ["Discours", "Débat"],
      ["Interview", "Conférence de presse"],
      ["Rumeur", "Ragot"],
      ["Annonce", "Publicité"],
      ["Signal", "Alarme"],
    ],
  },
  {
    name: "Temps & Horloge",
    pairs: [
      ["Matin", "Après-midi"],
      ["Nuit", "Soirée"],
      ["Semaine", "Week-end"],
      ["Minute", "Seconde"],
      ["Aujourd'hui", "Demain"],
      ["Passé", "Futur"],
      ["Retard", "Avance"],
    ],
  },
  {
    name: "Voyage & Vacances",
    pairs: [
      ["Valise", "Bagage à main"],
      ["Passeport", "Carte d'identité"],
      ["Billet d'avion", "Réservation"],
      ["Hôtel", "Location de vacances"],
      ["Guide touristique", "Carte routière"],
      ["Souvenir", "Carte postale"],
      ["Randonnée", "Excursion"],
      ["Croisière", "Safari"],
    ],
  },
  {
    name: "Amour & Relations",
    pairs: [
      ["Petit ami", "Petite amie"],
      ["Mariage", "Divorce"],
      ["Rendez-vous", "Sortie"],
      ["Câlin", "Bisou"],
      ["Demande en mariage", "Fiançailles"],
      ["Lune de miel", "Escapade romantique"],
    ],
  },
  {
    name: "Métiers artistiques",
    pairs: [
      ["Peintre", "Sculpteur"],
      ["Danseur", "Chorégraphe"],
      ["Poète", "Romancier"],
      ["Dessinateur", "Illustrateur"],
      ["Photographe", "Vidéaste"],
      ["Designer", "Styliste"],
    ],
  },
  {
    name: "Insectes & Petites bêtes",
    pairs: [
      ["Fourmi", "Termite"],
      ["Mouche", "Moustique"],
      ["Coccinelle", "Scarabée"],
      ["Chenille", "Ver de terre"],
      ["Grillon", "Sauterelle"],
      ["Mille-pattes", "Cloporte"],
    ],
  },
  {
    name: "Oiseaux",
    pairs: [
      ["Moineau", "Pigeon"],
      ["Pingouin", "Manchot"],
      ["Cygne", "Canard"],
      ["Colibri", "Mésange"],
      ["Pélican", "Héron"],
      ["Autruche", "Émeu"],
    ],
  },
  {
    name: "Armes & Défense (fiction)",
    pairs: [
      ["Épée", "Sabre"],
      ["Arc", "Arbalète"],
      ["Bouclier", "Armure"],
      ["Lance", "Hallebarde"],
      ["Catapulte", "Trébuchet"],
    ],
  },
  {
    name: "Matières & Textures",
    pairs: [
      ["Bois", "Bambou"],
      ["Métal", "Acier"],
      ["Plastique", "Caoutchouc"],
      ["Verre", "Cristal"],
      ["Coton", "Laine"],
      ["Cuir", "Daim"],
      ["Soie", "Velours"],
      ["Pierre", "Marbre"],
    ],
  },
  {
    name: "Marques & Applications",
    pairs: [
      ["TikTok", "Instagram"],
      ["iPhone", "Android"],
      ["Netflix", "Disney+"],
      ["PlayStation", "Xbox"],
      ["Google", "Bing"],
      ["Uber", "Bolt"],
      ["WhatsApp", "Messenger"],
      ["Amazon", "Cdiscount"],
      ["Spotify", "Deezer"],
      ["PayPal", "Revolut"],
      ["Zoom", "Teams"],
      ["YouTube", "Twitch"],
      ["Gmail", "Outlook"],
      ["Chrome", "Firefox"],
      ["Windows", "MacOS"],
    ],
  },
  {
    name: "Jeux vidéo",
    pairs: [
      ["Fortnite", "Minecraft"],
      ["Super Mario", "Sonic"],
      ["Pokémon", "Digimon"],
      ["FIFA", "PES"],
      ["GTA", "Red Dead Redemption"],
      ["League of Legends", "Dota"],
      ["Call of Duty", "Battlefield"],
      ["Zelda", "Final Fantasy"],
      ["Among Us", "Fall Guys"],
      ["Candy Crush", "Angry Birds"],
      ["Manette", "Clavier"],
      ["Console de salon", "Console portable"],
    ],
  },
  {
    name: "Franchises & Pop Culture",
    pairs: [
      ["Star Wars", "Star Trek"],
      ["Marvel", "DC"],
      ["Harry Potter", "Le Seigneur des Anneaux"],
      ["Pixar", "DreamWorks"],
      ["Batman", "Spider-Man"],
      ["Toy Story", "Shrek"],
      ["Jurassic Park", "King Kong"],
      ["Meme", "GIF"],
      ["Black Friday", "Cyber Monday"],
      ["Comic-Con", "Salon du jeu vidéo"],
      ["Disney princesse", "Poupée Barbie"],
      ["Émoji", "Autocollant"],
    ],
  },
  {
    name: "Monuments & Lieux touristiques",
    pairs: [
      ["Tour Eiffel", "Arc de Triomphe"],
      ["Grand Canyon", "Chutes du Niagara"],
      ["Disneyland", "Europa-Park"],
      ["Times Square", "Piccadilly Circus"],
      ["Mont Rushmore", "Statue de la Liberté"],
      ["Sacré-Cœur", "Notre-Dame"],
      ["Colisée", "Panthéon"],
      ["Big Ben", "Tour de Londres"],
      ["Mont Fuji", "Mont Blanc"],
      ["Pyramides de Gizeh", "Sphinx de Gizeh"],
      ["Machu Picchu", "Chichén Itzá"],
      ["Muraille de Chine", "Grande Barrière de Corail"],
    ],
  },
  {
    name: "Musique & Festivals",
    pairs: [
      ["Hip-hop", "R&B"],
      ["Country", "Folk"],
      ["Reggae", "Ska"],
      ["Victoires de la Musique", "NRJ Music Awards"],
      ["Coachella", "Lollapalooza"],
      ["Vinyle", "Cassette"],
      ["Boîte de nuit", "Bar karaoké"],
      ["DJ", "Producteur"],
      ["Tournée", "Concert unique"],
    ],
  },
  {
    name: "Réseaux & Communication numérique",
    pairs: [
      ["Story", "Publication"],
      ["Followers", "Amis"],
      ["Appel vidéo", "Appel audio"],
      ["Newsletter", "Notification push"],
      ["Forum", "Groupe de discussion"],
      ["Avatar", "Photo de profil"],
      ["Streaming", "Téléchargement"],
      ["Filtre", "Retouche photo"],
      ["Blogueur", "Vlogueur"],
      ["Modérateur", "Administrateur"],
    ],
  },
];
